import {
  PDFDocument,
  PDFTextField,
  PDFCheckBox,
  PDFRadioGroup,
  PDFDropdown,
  PDFOptionList,
  PDFButton,
  PDFSignature,
  type PDFField,
} from "pdf-lib";
import type { Field, FieldType, Form, Section } from "@/lib/form-model/types";
import { extractTextLayer } from "./text-layer";
import { resolveFieldPosition } from "./acroform-position";
import { nearbyLabelText } from "./nearby-text";

/**
 * Fast path from ARCHITECTURE.md §5.1: if a PDF has real AcroForm fields,
 * build the IR straight from the field dictionary. No OCR, no model call for
 * the field VALUES — exact fidelity, entirely local. The text layer is only
 * read to find each field's nearby label text, since many real-world forms
 * (this one included) name their fields meaninglessly ("001", "002", auto-
 * generated by whatever tool built the PDF) — see RISKS.html.
 */
export async function extractAcroForm(file: File): Promise<Form | null> {
  const bytes = await file.arrayBuffer();
  const pdf = await PDFDocument.load(bytes, { ignoreEncryption: true });
  const form = pdf.getForm();
  const acroFields = form.getFields();

  // Push buttons (e.g. a "Reset form" button) aren't a question to answer —
  // exclude them entirely rather than force them into the Field model.
  const dataFields = acroFields.filter((f) => !(f instanceof PDFButton));
  if (dataFields.length === 0) return null;

  // Best-effort: if this ever throws (encrypted/corrupt text layer), fields
  // just fall back to the humanized internal name below, same as before.
  const textLayer = await extractTextLayer(file).catch(() => null);

  const fields: Field[] = dataFields.map((acroField, index) => {
    const name = acroField.getName();
    const { type, options } = classify(acroField);

    const position = textLayer ? resolveFieldPosition(pdf, acroField) : null;
    const nearbyText = position && textLayer ? nearbyLabelText(position, textLayer.blocks) : "";
    const label = nearbyText || name;
    const hasRealLabel = nearbyText.length > 0;

    return {
      id: `field_${index}`,
      label,
      // A label found near the field on the page is far more likely to be
      // what a person would actually recognise than the field's own
      // internal name — but it's still not model-verified, so spokenLabel
      // stays literal (not rephrased as a question) and confidence stays
      // capped below the "detected with high confidence" band.
      spokenLabel: hasRealLabel ? label : humanize(name),
      type,
      required: false,
      constraints: options ? { options } : {},
      sensitivity: "none",
      confidence: hasRealLabel ? 0.55 : 0.4,
      anchor: { kind: "acroform", fieldName: name },
    };
  });

  const section: Section = { id: "section_1", fields };

  return {
    id: crypto.randomUUID(),
    title: file.name.replace(/\.pdf$/i, ""),
    source: "pdf",
    locale: "en-GB",
    provenance: {
      capturedAt: new Date().toISOString(),
      pageCount: pdf.getPageCount(),
      extractor: "acroform",
      localOnly: true,
    },
    sections: [section],
  };
}

function classify(acroField: PDFField): {
  type: FieldType;
  options?: { value: string; label: string }[];
} {
  if (acroField instanceof PDFCheckBox) return { type: "boolean" };
  if (acroField instanceof PDFRadioGroup) {
    return { type: "choice", options: acroField.getOptions().map((o) => ({ value: o, label: o })) };
  }
  if (acroField instanceof PDFDropdown) {
    return { type: "choice", options: acroField.getOptions().map((o) => ({ value: o, label: o })) };
  }
  if (acroField instanceof PDFOptionList) {
    return { type: "multichoice", options: acroField.getOptions().map((o) => ({ value: o, label: o })) };
  }
  if (acroField instanceof PDFTextField) {
    return { type: acroField.isMultiline() ? "longtext" : "text" };
  }
  if (acroField instanceof PDFSignature) return { type: "signature" };
  return { type: "unknown" };
}

/** "date_of_birth" / "DateOfBirth" -> "Date of birth". A stand-in until a model rewrite runs. */
function humanize(fieldName: string): string {
  const spaced = fieldName
    .replace(/[_-]+/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .trim();
  const lower = spaced.toLowerCase();
  return lower.charAt(0).toUpperCase() + lower.slice(1);
}
